sudo: required

services:
  - docker

before_install:
- docker pull alpine:3.4

script:
- IMAGE_NAME="bytejive/lazy-docker:snapshot-$TRAVIS_BUILD_NUMBER"
- docker build -t "$IMAGE_NAME" .
- docker run --rm "$IMAGE_NAME" pep8 .

